spring:
  application:
    name: sbb
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kdo
    username: root
    password: test1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
